# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd

In [0]:
from sklearn.datasets import load_iris

In [0]:
data = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = data.data 

In [0]:
y = data.target

In [52]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state =42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from keras.utils import to_categorical

In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
# Import `Sequential` from `keras.models`
from tensorflow.keras import layers


In [0]:
# Initialize the constructor
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Add an input layer 
model.add(layers.Dense(3, activation='sigmoid',input_shape=(4,)))

# Add an output layer 
model.add(layers.Dense(3, activation='softmax'))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])                  


## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [20]:
len(model.layers)

2

In [21]:
len(model.inputs)

1

In [22]:
len(model.outputs)

1

In [44]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 12        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.get_config()

{'layers': [{'class_name': 'Dense',
   'config': {'activation': 'sigmoid',
    'activity_regularizer': None,
    'batch_input_shape': (None, 4),
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'kernel_regularizer': None,
    'name': 'dense',
    'trainable': True,
    'units': 3,
    'use_bias': True}},
  {'class_name': 'Dense',
   'config': {'activation': 'softmax',
    'activity_regularizer': None,
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'kernel_regularizer': None,
    'name': 'dense_1',
    'trainable': True,
    'units': 3,
    'use_bia

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [45]:
print(X_train.shape)

(112, 4)


In [46]:
y_train.shape

(112, 3)

In [47]:
from keras.utils import to_categorical
model.fit(X_train, y_train,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 2s 21ms/sample - loss: 1.0498 - accuracy: 0.4196
Epoch 2/100
112/112 [==============================] - 0s 2ms/sample - loss: 1.0200 - accuracy: 0.4732
Epoch 3/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.9870 - accuracy: 0.5446
Epoch 4/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.9537 - accuracy: 0.6161
Epoch 5/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.9172 - accuracy: 0.6161
Epoch 6/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.8822 - accuracy: 0.6161
Epoch 7/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.8467 - accuracy: 0.6607
Epoch 8/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.8150 - accuracy: 0.6429
Epoch 9/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.7861 - accuracy: 0.6161
Epoch 10/100
112/112 [=============================

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
import numpy as np
y_pred = np.round(model.predict(X_test))

In [49]:
y_pred[0:10]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
y_classes = y_pred.argmax(axis=-1)

In [51]:
y_classes[0:10]

array([1, 0, 2, 1, 1, 0, 1, 1, 1, 1])



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [113]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [57]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [58]:
 # Check all the available files
 from google.colab import files
 !ls

prices.csv  sample_data


In [59]:
# Check all files present
!ls -al

total 50480
drwxr-xr-x 1 root root     4096 Jan 27 15:13 .
drwxr-xr-x 1 root root     4096 Jan 27 14:48 ..
drwxr-xr-x 1 root root     4096 Jan 13 16:38 .config
-rw-r--r-- 1 root root 51667341 Jan 27 15:28 prices.csv
drwxr-xr-x 1 root root     4096 Jan 13 16:38 sample_data


In [0]:
 # deleting a file
# !rm 'prices (1).csv'

In [0]:
import pandas as pd
data_Stock = pd.read_csv('prices.csv')
# Dataset is now stored in a Pandas Dataframe

In [115]:
data_Stock.head(2)

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0

[2 rows x 7 columns]

In [116]:
data_Stock.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
### Drop columnns
data_Stock = data_Stock.drop(labels = ['date','symbol'], axis = 1)

In [118]:
data_Stock.head(2)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0

In [119]:
data_Stock.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
data_StockSample = data_Stock.iloc[0:1000]

In [121]:
len(data_StockSample)

1000

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X_stock = data_StockSample.iloc[:,0:4]

In [123]:
X_stock.head(2)

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001

In [124]:
X_stock.shape

(1000, 4)

In [0]:
y_stock = data_StockSample['volume']

In [126]:
y_stock.iloc[0:5]

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
Name: volume, dtype: float64

In [127]:
y_stock.shape

(1000,)

In [0]:
y_stock = y_stock /1000000

In [129]:
y_stock.iloc[0:5]

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np
X_stock = np.array(X_stock)
y_stock = np.array(y_stock)

In [0]:
X_stock = X_stock.astype('float32')
y_stock = y_stock.astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X_stock = tf.math.l2_normalize(X_stock,axis=None,epsilon=1e-12,name=None)

In [133]:
X_stock

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.00799559, 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(features, W, b):
    y_pred = tf.add(tf.matmul(features, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg


## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

Define the model

In [0]:
def train(x, y, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [137]:
for i in range(100): 
#for i in range(5):    
    W, b = train(X_stock, y_stock, W, b)
    print('Current Training Loss on iteration', i, loss(y_stock, prediction(X_stock, W, b)).numpy())

Current Training Loss on iteration 0 236.16774
Current Training Loss on iteration 1 235.09312
Current Training Loss on iteration 2 234.06105
Current Training Loss on iteration 3 233.06989
Current Training Loss on iteration 4 232.11801
Current Training Loss on iteration 5 231.20384
Current Training Loss on iteration 6 230.32588
Current Training Loss on iteration 7 229.48273
Current Training Loss on iteration 8 228.67294
Current Training Loss on iteration 9 227.89528
Current Training Loss on iteration 10 227.14842
Current Training Loss on iteration 11 226.43115
Current Training Loss on iteration 12 225.74232
Current Training Loss on iteration 13 225.08076
Current Training Loss on iteration 14 224.4454
Current Training Loss on iteration 15 223.83525
Current Training Loss on iteration 16 223.24927
Current Training Loss on iteration 17 222.68648
Current Training Loss on iteration 18 222.14601
Current Training Loss on iteration 19 221.62694
Current Training Loss on iteration 20 221.12846
Cur

### Observe values of Weight
- Print the updated values

In [138]:
print(W)

tf.Tensor(
[[0.0547828 ]
 [0.0548819 ]
 [0.05422734]
 [0.05533116]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [139]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
